portfolio/home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name="home"),
    path('project/', views.project, name="portfolio"),
    path('skill/', views.skill, name="skill"),
    path('contact/', views.contact, name="contact")
]

portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

portfolio/home/models.py
from django.db import models

# Create your models here.

portfolio/home/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'home/home.html',{'title':'Home'})

def project(request):
    return render(request, 'home/project.html',{'title':'Project'})

def skill(request):
    return render(request, 'home/skill.html',{'title':'Skill'})

def contact(request):
    return render(request, 'home/contact.html',{'title':'Contact'})

portfolio/templates/home/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
     <!-- Google Fonts -->
     <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:wght@300;600;700&display=swap" rel="stylesheet">
     <!-- Font Awesome -->
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
     <!-- CSS Files -->
     <link rel="stylesheet" href="{% static 'home/css./grid.css' %}">
     <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
     <link rel="stylesheet" href="{% static 'home/css/responsive.css' %}">
     
    
</head>
<body>
    <nav>
        <div class="row">
                 <a class="logo" href="{% url 'home:home' %}">SAMRAT HOSSAIN</a>
            <ul class="nav-menu">
                <li><a href="{% url 'home:home' %}">home</a></li>
                <li><a href="{% url 'home:portfolio' %}">project</a></li>
                <li><a href="{% url 'home:skill' %}">skill</a></li>
                <li><a href="#">blog</a></li>
                <li><a href="{% url 'home:contact' %}">contact</a></li>
            </ul>
        </div>
    </nav>
   
    {% block body %}

    {% endblock %}

    

    <!-- JS Files -->
    <script src="{% static 'home/js/html5shiv.min.js' %}"></script>
    <script src="{% static 'home/js/respond.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'home/js/main.js' %}"></script>

</body>
</html>

portfolio/templates/home/contact.html
{% extends 'home/base.html' %}

{% block body %}

<section class="contact-section">
    <div class="row">
        <h2>contact with me</h2>
        <p>If you have any question, feel free to send me a message</p>
    </div>
    <form action="https://formspree.io/f/mjvproav" method="POST">
        <div class="row">
            <div class="col span_1_of_2">
                <input type="text" placeholder="Your Name *" name="name" required>
            </div>
            <div class="col span_1_of_2">
                <input type="email" placeholder="Your Email *" required>
            </div>
        </div>
        <div class="row">
            <textarea name="message" cols="30" rows="10" placeholder="Your Message *" required></textarea>
        </div>
        <div class="row btn-message">
            <input class="btn-send-message" type="submit" value="Send Message">
        </div>
    </form>
</section>

{% endblock %}

portfolio/templates/home/home.html
{% extends 'home/base.html' %}
{% load static %}

{% block body %}

<section class="body-section">
    <div class="row">
        <div class="col span_1_of_2 content">
            <h2>Hey, I am SAMRAT</h2>
            <p>I am a professional full stack web application developer. I will create responsive website for your business.</p>
            <div class="project-btn">
                <button>My Project</button>
            </div>
            <div class="social-icon">
                <ul>
                    <li><a href="https://www.facebook.com/samratsr99" target="blank">
                        <i class="fa fa-facebook" aria-hidden="true"></i>
                    </a></li>
                    <li><a href="https://www.linkedin.com/in/samrathossain/" target="blank">
                        <i class="fa fa-linkedin" aria-hidden="true"></i>
                    </a></li>
                    <li><a href="https://github.com/SamratHossain" target="blank">
                        <i class="fa fa-github" aria-hidden="true"></i>
                    </a></li>
                    <li><a href="https://www.instagram.com/samraat_hossain/" target="blank">
                        <i class="fa fa-instagram" aria-hidden="true"></i>
                    </a></li>
                </ul>
            </div>
        </div>
        <div class="col span_1_of_2 home-img">
            <img src="{% static 'home/images/home-img.jpg' %}" alt="">
        </div>
    </div>
</section>

{% endblock %}

portfolio/templates/home/portfolio.html
{% extends 'home/base.html' %}

{% block body %}

{% endblock %}

portfolio/templates/home/project.html
{% extends 'home/base.html' %}

{% block body %}

{% endblock %}

portfolio/templates/home/skill.html
{% extends 'home/base.html' %}
{% load static %}

{% block body %}

<section class="skill-section">
    <div class="row">
            <h2>My Skills</h2>
            <p>As a Developer, I love taking challenges and love being part of the solution.</p>
    </div>
    <div class="row">
        <div class="col span_1_of_2">
            <h3>FrontEnd</h3>
            <div class="main">
                <div class="progressBar">
                    <div class="title htmlColor">HTML5</div>
                    <div class="progress html"></div>
                    <div class="progress_value">90%</div>
                </div>
                <div class="progressBar">
                    <div class="title cssColor">CSS3</div>
                    <div class="progress css"></div> 
                    <div class="progress_value">75%</div>
                </div>
                <div class="progressBar">
                    <div class="title jsColor">Bootstrap</div>
                    <div class="progress js"></div>
                    <div class="progress_value">80%</div>
                </div>
                <div class="progressBar">
                    <div class="title bootstrapColor">JavaScript</div>
                    <div class="progress bootstrap"></div>
                    <div class="progress_value">70%</div>
                </div>
            </div>
        </div>
        <div class="col span_1_of_2">
            <h3>BackEnd</h3>
            <div class="main">
                <div class="progressBar">
                    <div class="title htmlColor">Python</div>
                    <div class="progress html"></div>
                    <div class="progress_value">90%</div>
                </div>
                <div class="progressBar">
                    <div class="title cssColor">Django</div>
                    <div class="progress css"></div> 
                    <div class="progress_value">75%</div>
                </div>
                <div class="progressBar">
                    <div class="title jsColor">PostgreSQL</div>
                    <div class="progress js"></div>
                    <div class="progress_value">80%</div>
                </div>
                <div class="progressBar">
                    <div class="title bootstrapColor">MySQL</div>
                    <div class="progress bootstrap"></div>
                    <div class="progress_value">70%</div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="education-section">
    <div class="row">
        <div class="col span_1_of_2 education">
            <h2>education</h2>
            <div class="degree">
                <h1>B.sc in Computer Science and Engineering</h3>
                <h3>Institute of Science and Technology</h3>
                <h4>2017-running</h4>
            </div>
            <div class="degree">
                <h1>Higher Secondary Certificate(HSC)</h3>
                <h3>Dohar-Nawabgonj College</h3>
                <h4>2014-2016</h4>
            </div>
            <div class="degree">
                <h1>Secondary School Certificate(SSC)</h3>
                <h3>Barrah Habil Uddin High School</h3>
                <h4>2009-2013</h4>
            </div>
        </div>
        <div class="col span_1_of_2 experience">
            <h2>Working Exprience</h2>
            <div class="project">
                <h3>Project: Enrollment System</h3>
                <p>In this system administration keeps students information during admission. Administration can make any query regarding a student using a search option and also adding new record, save record, update record and delete record.</p>
                <h4>Technology: Python, Django, PostgreSQL, HTML5, CSS3, Bootstrap</h4>
            </div>
        </div>
    </div>
</section>

{% endblock %}